//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define IDS_DBG_STR_START               1
#define IDS_LVCOL01                     2
#define IDS_LVCOL02                     3
#define IDS_LVCOL03                     4
#define IDS_LVCOL04                     5
#define IDS_LVCOL05                     6
#define IDS_LVCOL06                     7
#define IDD_MEMVIEW                     103
#define IDD_ABOUT                       104
#define IDI_NDC_ICON                    105
#define IDI_BRKPT                       110
#define IDI_BRKPTDIS                    111
#define IDD_SH4DEBUG                    112
#define IDD_MEMVIEW__                   113
#define IDD_DISVIEW                     115
#define IDD_PVRVIEW                     116
#define IDD_PLUGIN_SELECT               118
#define IDD_CONFIG                      119
#define IDI_ICON2                       120
#define IDD_PROFILER                    121
#define IDR_NDC_LOGO                    124
#define IDC_CUSTOM                      1001
#define IDC_SEARCH                      1003
#define IDC_FIND                        1004
#define IDS_R0                          1007
#define IDS_R1                          1008
#define IDS_R2                          1009
#define IDS_R3                          1010
#define IDS_R4                          1011
#define IDS_R5                          1012
#define IDS_R6                          1013
#define IDS_R7                          1014
#define IDS_R8                          1015
#define IDS_R9                          1016
#define IDS_R10                         1017
#define IDS_R11                         1018
#define IDS_R12                         1019
#define IDS_R13                         1020
#define IDS_R14                         1021
#define IDS_R15                         1022
#define IDS_GBR                         1023
#define IDS_PR                          1024
#define IDS_SSR                         1025
#define IDS_SPC                         1026
#define IDS_VBR                         1027
#define IDS_SGR                         1028
#define IDS_DBR                         1029
#define IDS_B0                          1030
#define IDS_B1                          1031
#define IDS_B2                          1032
#define IDS_B3                          1033
#define IDS_B4                          1034
#define IDS_B5                          1035
#define IDS_B6                          1036
#define IDS_B7                          1037
#define IDB_STEP                        1038
#define IDC_MEMSEL                      1039
#define IDS_SR_S                        1040
#define IDC_DISASMVIEW                  1041
#define IDS_SR_Q                        1042
#define IDS_SR_M                        1043
#define IDS_SR_BL                       1044
#define IDS_MACH                        1045
#define IDS_MACL                        1046
#define IDS_SR_IMASK                    1047
#define IDS_PC                          1048
#define IDS_FPSCR                       1049
#define IDS_FPUL                        1050
#define IDS_SR_FD                       1051
#define IDS_SR_RB                       1052
#define IDS_SR_MD                       1053
#define IDS_SR_T                        1054
#define IDC_ADDR                        1057
#define IDB_GOTO                        1058
#define IDS_FR0                         1059
#define IDC_ADDR2                       1059
#define IDC_MBPADDR                     1059
#define IDS_FR1                         1060
#define IDS_FR2                         1061
#define IDS_FR3                         1062
#define IDS_FR4                         1063
#define IDS_FR5                         1064
#define IDS_FR6                         1065
#define IDS_FR7                         1066
#define IDS_FR8                         1067
#define IDS_FR9                         1068
#define IDS_FR10                        1069
#define IDS_FR11                        1070
#define IDS_FR12                        1071
#define IDS_FR13                        1072
#define IDS_FR14                        1073
#define IDS_FR15                        1074
#define IDB_STOP                        1075
#define IDC_VIEWSEL                     1076
#define IDB_START                       1078
#define IDC_VIEW                        1078
#define IDB_SKIP                        1079
#define IDS_CCR                         1080
#define IDS_QACR0                       1081
#define IDS_QACR1                       1082
#define IDS_MMUCR                       1083
#define IDS_FPUREGS                     1084
#define IDC_FPSEL1                      1085
#define IDC_FPSEL2                      1086
#define IDC_FPSEL3                      1087
#define IDB_START2                      1088
#define IDB_REMOVEMBP                   1088
#define IDB_ADDMBP                      1089
#define IDC_CHECK3                      1090
#define IDC_EDIT1                       1091
#define IDC_MAPLESUB1                   1091
#define IDC_THXLIST                     1091
#define IDC_XF                          1092
#define IDS_CallStack                   1093
#define IDC_CALLSTACK                   1095
#define IDC_EDIT2                       1096
#define IDC_COMBO1                      1097
#define IDC_C_PVR                       1097
#define IDC_COMBO2                      1098
#define IDC_C_GDR                       1098
#define IDC_PVR_CONF                    1099
#define IDC_C_GDR3                      1100
#define IDC_C_AICA                      1100
#define IDC_REC                         1100
#define IDC_GDR_CONF                    1101
#define IDC_C_ARM                       1101
#define IDC_BUTTON3                     1102
#define IDC_AICA_CONF                   1102
#define IDC_C_EXTDEV                    1105
#define IDC_AICA_CONF2                  1106
#define IDC_EXTDEV_CONF                 1106
#define IDC_COMBO6                      1107
#define IDC_MAPLEPORT                   1107
#define IDC_MAPLEMAIN                   1108
#define IDC_MAPLESUB0                   1109
#define IDC_TAB1                        1110
#define IDC_MAPLESUB2                   1111
#define IDC_MAPLESUB3                   1112
#define IDC_MAPLESUB4                   1113
#define IDC_MAPLETAB                    1114
#define IDC_NDC_VER                     1115
#define IDC_REC_CPP                     1116
#define IDC_REC_UFPU                    1117
#define IDC_PROFTEXT                    1118
#define IDC_BUTTON1                     1119
#define IDC_COPY                        1119
#define ID_DEBUG_REGVIEWER              40008
#define ID_DEBUG_DISASMVIEWER           40009
#define ID_HELP_HOWTO                   40013
#define ID_OPTIONS_SELECTPLUGIN         40021
#define ID_FILE_BOOTGDROM               40023
#define ID_FILE_D                       40024
#define ID_OPTIONS_CONFIGURE            40026
#define ID_PROFILER_SHOW40031           40031
#define ID_OPTIONS_POWERVR              40033
#define ID_OPTIONS_G                    40034
#define ID_OPTIONS_AICA                 40035
#define ID_OPTIONS_MAPLE                40036
#define ID_OPTIONS_EXT                  40039

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40044
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
